### ISSUE TITLE
Possible to set max payload size?

### ISSUE THREAD

**Issue by hehachris** [zrrrzzt/docker-unoconv-webservice#1]
Currently I am getting `Payload content length greater than maximum allowed: 1048576` if the file is too large.

**Comment by zrrrzzt** [comment]
The default filesize is set to 1048576 (1 MB). It is possible to adjust this in the settings for Hapi http://hapijs.com/api#route-options

Would it be enough for you @hehachris if I enabled adjusting the size through Dockers ENV-variables?

**Comment by hehachris** [comment]
@zrrrzzt that would be great, thanks a lot!

**Comment by hehachris** [comment]
thanks @zrrrzzt !

**Comment by zrrrzzt** [comment]
np :-)
