### ISSUE TITLE
pdf to html/pdf to odt

### ISSUE THREAD

**Issue by lvsenlin** [zrrrzzt/docker-unoconv-webservice#17]
Error: :1: parser error : Document is empty
%PDF-1.4
^
:1: parser error : Document is empty
%PDF-1.4
^
:1: parser error : Document is empty
%PDF-1.4
^

    at ChildProcess.<anonymous> (/unoconvservice/node_modules/unoconv2/index.js:58:29)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
/unoconvservice/uploads/19dcdc80-ec92-4905-b3d1-56d930265712.pdf deleted

**Comment by zrrrzzt** [comment]
Need a bit more information to be able to help you.

- What command did you use to upload the file?
- Does all your conversions fail or just this one?

**Comment by lvsenlin** [comment]
I use this command:
curl --form file=@1.pdf http://localhost/unoconv/html > 1.html
other conversions success,just pdf to html/word

**Comment by zrrrzzt** [comment]
It might look as pdf => html not is supported by LibreOffice (which is the software doing the conversion).

I tried to do a direct conversion from the cli

```
soffice --headless --convert-to html myfile.pdf
```

and the result was just garbled text.

In that case there's nothing I can do to make it work.

**Comment by lvsenlin** [comment]
if use the libreoffice client,it can convert html with images.

**Comment by zrrrzzt** [comment]
Can you share the command you used?

**Comment by lvsenlin** [comment]
A perfect plan, use ubuntu image, command use this:
`/usr/lib/libreoffice/program/soffice --convert-to xhtml 1.pdf`
Later, I'll release a image

**Comment by zrrrzzt** [comment]
yup, that's correct.

Your cli command work and ```curl --form file=@myfile.pdf http://localhost/unoconv/xhtml > myfile.xhtml```does not work very well.

It might seem like unoconv (one of the underlying modules) might be the problem. I did some tests using soffice directly from node using exec and pdf => xhtml conversion worked.

Maybe I'll release a webservice later without unoconv in the middle. Good to see you solved your problem at least :-)
