### ISSUE TITLE
converting PPT and/or ODP to HTML

### ISSUE THREAD

**Issue by kadevgraaf** [zrrrzzt/docker-unoconv-webservice#2]
Hi Geir,

Thanks for making the nice unoconv-webservice available.

I am trying to convert PPT(X) and ODP to HTML using the webservice in a docker container, e.g., using 
curl --form file=@myfile.ppt http://<hostname>:6000/unoconv/html > myfile.html
and 
curl --form file=@myfile.odt http://<hostname>:6000/unoconv/html > myfile.html

However, the resulting myfile.html is 0 bytes.

Several other conversions work nice though (docx -> html and pptx -> PDF), but I want to convert from common presentation format to HTML.
I looked up the possible input/outputs on http://dag.wiee.rs/home-made/unoconv/ and the conversion seems possible (e.g., a conversion that is not possible --form file=@myfile.ppt http://<hostname>:6000/unoconv/xhtml > myfile.xml gives an error: {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"} which might be expected, but conversion to HTML does not give any result).
I also looked at https://github.com/zrrrzzt/tfk-api-unoconv and https://github.com/dagwieers/unoconv for a solution, but without results. 

Do you know how I can fix this, e.g., whether I should set some output filter options?

Or would it be most practical to install https://github.com/dagwieers/unoconv and set the necessary (output filter) configuration by hand and/or create my own webservice?

Thanks,

Klaas

**Comment by zrrrzzt** [comment]
Thanks for your interest in this project. 
I just put it together for docx -> pdf convertions. The rest is just a nice bonus.

Unfortunately I don't have much spare time these days to help find a solution to your particular problem. 
One possibility is that a pptx would create more than one file. This service just handles one file in => one file out. But this is just a wild guess.

If you need absolute control for your project I would recommend to install it yourself or spin up one of the many dockerfiles for unoconv. If I remember correct this was my starting point https://hub.docker.com/r/pataquets/unoconv-server

**Comment by kadevgraaf** [comment]
Thanks for your (quick) reply!
Indeed this could be the case because the 'save as' -> html option in Openoffice desktop installation gives you multiple html files in most cases (there is a single html file option, but this conversion is not what I am looking for).
