### ISSUE TITLE
example using php cUrl

### ISSUE THREAD

**Issue by robertzimmerman** [zrrrzzt/docker-unoconv-webservice#21]
would you have an example of using your service with PHP cUrl? I am having a lot of trouble getting it to work. normally getting a blank pdf file back.

**Comment by zrrrzzt** [comment]
I'm sorry. I have not used php in a very long time :-(
If you are in an environment where you can test the cUrl example from the README you would be able to confirm that the service works as expected. If it does you know there's something in your code, if it doesn't I have to dig deeper.

Btw I just found this the other day: https://github.com/thecodingmachine/gotenberg I think they offer a PHP-client.

**Comment by robertzimmerman** [comment]
@zrrrzzt thank you for the reference. Looks like a good php-client.

**Comment by joanfabregat** [comment]
I wrote a simple PHP client for the API. It's available on [GitHub](https://github.com/codeinchq/unoconv-webservice-client) and [Packagist](https://packagist.org/packages/codeinc/unoconv-webservice-client) under the MIT license. 


You can install the client using Composer:
```sh
composer require codeinc/unoconv-webservice-client
```
