### ISSUE TITLE
Is there a possibility to upgrade to libreoffice manually or change Dockerfile?

### ISSUE THREAD

**Issue by janmottl** [zrrrzzt/docker-unoconv-webservice#26]
Is there a possibility to upgrade to libreoffice7 manually or change Dockerfile? Thanks for advice.
I tried to uninstall libreoffice6 and install libreoffice7 manually in existing container. But it doesn't work.
libreoffice6 has problem with customer's odts.

**Comment by janmottl** [comment]
Finally we have found a way how to change document template to prevent libreoffice6 problem. But libreoffice7 would be appreciated.

**Comment by zrrrzzt** [comment]
I don't have the time at the moment to update the docker image and test it. But PRs are welcome :-)
This is the base docker image https://github.com/telemark/docker-node-unoconv
