### ISSUE TITLE
Extend webservice to support obtaining unoconv version and supported formats

### ISSUE THREAD

**Issue by euven** [zrrrzzt/docker-unoconv-webservice#4]
Hi there,

Thanks for this - it works great and saves a lot of hassle ;)

To help with preventing errors, would it be possible to call the webservice and obtain version and support format information?

Thanks,
Eugene.

**Comment by zrrrzzt** [comment]
You're welcome @eugeneventer 

I like your idea. I have opened an issue over at https://github.com/zrrrzzt/tfk-api-unoconv/issues/1 (that is the actual webservice)

Could you add a couple of lines in the new thread with some example of how you would like input/output to function.
